In [5]:
#操作csv文件
# 1、文件保存
import numpy as np
array=np.random.randint(0,9,size=(3,5))
np.savetxt("array.csv",array,fmt="%d",delimiter=",")


In [12]:
# 2、读取文件
c=np.loadtxt("array.csv",dtype="int",delimiter=",",unpack=True)
print(c)

[[1 1 6]
 [1 3 7]
 [4 0 7]
 [3 4 4]
 [2 4 3]]


In [16]:
#np独有存储方式
# 保存数组
np.save("数组1",array)
np.savez("数组2",array)   #保存为压缩文件
# 读取数组
a=np.load("数组1.npy")
a1=np.load("数组2.npz") #读取压缩文件(格式)
print(a)
print(a1)

[[1 1 4 3 2]
 [1 3 0 4 4]
 [6 7 7 4 3]]


In [24]:
# csv文件操作
#读取csv文件
import csv
with open("array.csv",'r') as rp:
    reader=csv.reader(rp)
    #迭代标题
    titles=next(reader)
    for i in reader:
        print(i)
#使用DictReader
with open("array.csv","r") as fp1:
    reader=csv.DictReader(fp1)
    for i in reader:
        print(i["键名"])
    

['1', '3', '0', '4', '4']
['6', '7', '7', '4', '3']


KeyError: 1

In [26]:
# 写入csv文件
headers = ['name','age','classroom']
values = [
 ('zhiliao',18,'111'),
 ('wena',20,'222'),
 ('bbc',21,'111') ]

with open("writer.csv",'w',newline='') as fw:
    writer=csv.writer(fw)
    writer.writerow(headers)
    writer.writerows(values)
# DictWriter
headers = ['name','age','classroom']
values = [
 {"name":'wenn',"age":20,"classroom":'222'},
 {"name":'abc',"age":30,"classroom":'333'} ]
with open("writer1.csv",'w',newline='') as fw1:
    wirter=csv.DictWriter(fw1,headers)
    writer.writerow({"name":'wenn',"age":20,"classroom":'222'})
    writer.writerows(values)


In [28]:
#数组操作和文件操作作业
a = np.random.rand(3,2,3)
b = np.random.rand(3,2,2)
c =np.random.rand(3,1,1)
# print(a+b)
print(a+c)

[[[1.79008941 1.40839384 1.80323607]
  [1.14872473 1.41564645 1.13035416]]

 [[0.78729596 0.7490743  1.24072296]
  [1.11080294 0.69938256 1.09116685]]

 [[0.10579056 0.70946187 0.13494067]
  [0.6504809  0.4688017  0.68463977]]]


In [51]:
# 2、
a = np.random.rand(3,5)
b = np.random.rand(6,4)
c2=np.full((6,1),0)
b1=np.hsplit(b,2)
print(a)
print("a*****************")
print(b)
print("b*****************")
print("***************************")
# print(np.hstack([a,c1]))
result=np.vstack([a,np.hstack([np.hstack([b1[0],c2]),b1[1]])])
print(result)

[[0.49814687 0.32467839 0.46048981 0.18190831 0.01921961]
 [0.56840901 0.22287907 0.42019336 0.71476728 0.8631225 ]
 [0.22512977 0.35812676 0.52473552 0.04905428 0.55484875]]
a*****************
[[0.78882706 0.75275682 0.58450169 0.64159086]
 [0.10861232 0.78449721 0.34033182 0.75412037]
 [0.54528403 0.40536608 0.13427058 0.73653286]
 [0.64544358 0.63029123 0.8118314  0.11448718]
 [0.6206394  0.91863697 0.14143358 0.22079504]
 [0.05706996 0.16457428 0.78421271 0.57477418]]
b*****************
***************************
[[0.49814687 0.32467839 0.46048981 0.18190831 0.01921961]
 [0.56840901 0.22287907 0.42019336 0.71476728 0.8631225 ]
 [0.22512977 0.35812676 0.52473552 0.04905428 0.55484875]
 [0.78882706 0.75275682 0.         0.58450169 0.64159086]
 [0.10861232 0.78449721 0.         0.34033182 0.75412037]
 [0.54528403 0.40536608 0.         0.13427058 0.73653286]
 [0.64544358 0.63029123 0.         0.8118314  0.11448718]
 [0.6206394  0.91863697 0.         0.14143358 0.22079504]
 [0.05706996

In [98]:
# NAN和INF值处理
arr=np.random.randint(0,9,size=(5,6)).astype(np.float)
arr[0,3]=np.nan
arr[2,5]=np.nan
#1、删除所有缺失值
b=arr[~np.isnan(arr)]
# print(b)
# 2、删除nan所在的行
print(arr)
print(np.where(np.isnan(arr)))  #使用where函数获得nan在数组中的位置，返回元组，前面代表行号，后面代表列号
lines=np.where(np.isnan(arr))[0]
data=np.delete(arr,lines,axis=0)
print(data)
# np.where(np.isnan(arr))



[[ 5.  3.  8. nan  4.  1.]
 [ 4.  0.  1.  6.  4.  0.]
 [ 4.  7.  4.  0.  0. nan]
 [ 2.  7.  0.  7.  3.  1.]
 [ 4.  1.  3.  1.  0.  5.]]
(array([0, 2], dtype=int64), array([3, 5], dtype=int64))
[[4. 0. 1. 6. 4. 0.]
 [2. 7. 0. 7. 3. 1.]
 [4. 1. 3. 1. 0. 5.]]


In [120]:
# 3、用其他值替换
scores = np.loadtxt("scores.csv",skiprows=1,delimiter=",",encoding="utf-8",dtype=np.str)  #读物csv文件的值
scores[scores=='']=np.NAN  #将数组中所有空值都等于nan
scores[scores == ""] = np.NAN
scores=scores.astype(np.float)
# print(scores)
# 1. 求出学生成绩的总分
score1=scores.copy()
# print(score1.sum(axis=1))
# 1. 求出学生成绩的平均分
score2=scores.copy()
# print(score2.shape)
for i in range(score2.shape[1]):
    score=scores[:,i]
    avage=score[~np.isnan(score)].mean()
    score[np.isnan(score)]=avage
print(scores)

[[59. 89.]
 [90. 32.]
 [78. 45.]
 [34. nan]
 [nan 56.]
 [90. 56.]]
[[59.  89. ]
 [90.  32. ]
 [78.  45. ]
 [34.  55.6]
 [70.2 56. ]
 [90.  56. ]]


In [145]:
# random模块 
#random.seed(种子值)
#np.random.seed(1) 如果设置即随机数固定，如果不设置，则默认种子值为时间戳


#  np.random.rand([行，列])  0-1之间的小数
# a=np.random.rand(2,3)  
#  np.random.randn([行，列])  随即标准正态分布值
# a=np.random.randn(2,3)
# print(a)


    # np.random.choice(数字或数组,[行，列])  ；从数字或数组中随机选取0个或多个数据，可以构成数组
data=np.arange(10)
# a=np.random.choice(data,size=(2,3))
# a=np.random.choice(data,3)
# a=np.random.choice(10,3)
# print(a)

np.random.shuffle(data)  #将数组中数据顺序打乱
print(data)



[6 4 3 5 2 0 8 9 1 7]


In [164]:
#通用函数
# np.abs() 绝对值函数
n=-1
a=np.abs(n)
print(a)

# np.sqrt() 平方根函数 
n=4
b=np.sqrt(n)
print(b)

# np.square()  平方函数
b=np.square(n)
print(b)

#np.exp() 指数函数 e的x次方

n=4
b=np.exp(n)  
print(b)

#np.log，np.log10，np.log2，np.log1p   求以e为底，以10为低，以2为低，以(1+x)为底的对数
b=np.log(n)  
print(b)

b=np.log10(n)  
print(b)

b=np.log2(n)  
print(b)

b=np.log1p(n)  
print(b)


# np.sign() 将数组中的值标签化，大于0的变成1，等于0的变成0，小于0的变成-1
b=np.sign(2)
print(b)

# np.ceil() 朝着无穷大的方向取整，比如5.1会变成6，-6.3会变成-6
np.ceil(5.1)


# np.floor() 朝着负无穷大方向取证，比如5.1会变成5，-6.3会变成-7
np.floor(5.8) 


#np.rint，np.round  返回四舍五入后的值
print(np.rint(5.5))
print(np.round(5.5))


#np.modf  将整数和小数分隔开来形成两个数组
print(np.modf(3.4))  

#np.isnan()   判断是否是nan
n=np.nan
print(np.isnan(n))

#np.isinf()   判断是否是inf
n=np.inf
print(np.isinf(n)) 

#np.cos，np.cosh，np.sin，np.sinh，np.tan，np.tanh   三角函数
#np.arccos，np.arcsin，np.arctan  反三角函数

1
2.0
16
54.598150033144236
1.3862943611198906
0.6020599913279624
2.0
1.6094379124341003
1
6.0
6.0
(0.3999999999999999, 3.0)
True
True


In [165]:
#二元函数
# np.add   加法运算（即1+1=2），相当于+
print(np.add(1,1))

# np.subtract 减法运算（即3-2=1），相当于-
print(np.subtract(3,2))

# np.multiply 乘法运算（即3*2=6），相当于*
print(np.multiply(2,2))

# np.divide 除法运算（即6/2=3），相当于、
print(np.divide(6,2))

# np.negative负数运算（即-2），相当于加个负号
print(np.negative(2))

# np.floor_divide 取整运算，相当于//
print(np.floor_divide(4,3))

# np.mod 取余运算，相当于%
print(np.mod(8,3))

# greater,greater_equal,less,less_equal,equal,not_equal >,>=,<,<=,=,!=的函数
# 表达式
print(np.greater(3,1))
print(np.greater_equal(3,3))
print(np.less(2,5))
print(np.less_equal(2,2))
print(np.not_equal(2,5))

# logical_and &的函数表达式
# logical_or \
print(np.logical_and(1,2))
print(np.logical_or(1,2))

2
1
4
3.0
-2
1
2
True
True
True
True
True
True
True


In [166]:
# 3、聚合函数
# 函数名称 NAN安全版本 描述
# np.sum np.nansum 计算元素的和
# np.prod np.nanprod 计算元素的积
# np.mean np.nanmean 计算元素的平均值
# np.std np.nanstd 计算元素的标准差
# np.var np.nanvar 计算元素的方差
# np.min np.nanmin 计算元素的最小值
# np.max np.nanmax 计算元素的最大值
# np.argmin np.nanargmin 找出最小值的索引
# np.argmax np.nanargmax 找出最大值的索引
# np.median np.nanmedian 计算元素的中位数

In [167]:
# 布尔数组的函数
# np.any 验证任何一个元素是否为真
# np.all 验证所有元素是否为真
print(np.any(0))
print(np.all([0,1,2]))



False
False


In [168]:
# np.linspace：用来将指定区间内的值平均分成多少份。
print(np.linspace(0,1,12))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [170]:
np.full((3,3),False,dtype=np.bool)
np.full((3,3),False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])