In [7]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]],np.int32)
# x.shape
# x.dtype
# x[1,1]
y=x[:,1]
y

array([2, 5])

In [8]:
y[0] = 7
y

array([7, 5])

In [9]:
x

array([[1, 7, 3],
       [4, 5, 6]])

In [38]:
# x.flags #获取内存布局信息
# x.shape   #数组维度的元组
# x.strides   #遍历数组时每个维度中的字节元组  (12, 4)
# x.ndim   #数组维度
# x.data   #Python缓存区对象指向数组的数据的开头
# x.size   #数组中元素的个数
# x.itemsize   #一个数组元素的长度，以字节为单位   4
# x.nbytes   #数组元素消耗的总字节数
x.base   #如果内存来自其他对象，则为基础对象

In [55]:
# 其他属性
# ndarray.T	转置数组。
x.T
# ndarray.real	数组的真实部分。
x.real
# ndarray.imag	数组的虚部。
x.imag
# ndarray.flat	数组上的一维迭代器。
x.flat    #<numpy.flatiter at 0x2ba3c4b78d0>

# ndarray.ctypes	一个简化数组与ctypes模块交互的对象。
x.ctypes     #<numpy.core._internal._ctypes at 0x2ba3fa5ca08>
x

array([[1, 7, 3],
       [4, 5, 6]])

In [6]:
"""数组方法"""
"""
numpy：
    all，any，argmax， argmin，argpartition，argsort，choose，
    clip，compress，copy，cumprod， cumsum，diagonal，imag，max，
    mean，min，nonzero，partition， prod，ptp，put，ravel，real，
    repeat，reshape，round， searchsorted，sort，squeeze，std，
    sum，swapaxes，take，trace， transpose，var
"""
#数组转换

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item
#ndarray.item(*args)  将数组元素复制到标准的Python标量并返回它
# x.item(1)
# x.item(1,2)   #数字为一个，则代表数组下标，如果为两个数，则代表行列索引

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.tolist.html#numpy.ndarray.tolist
# ndarray.tolist()  将数组作为a.ndim-levels深层嵌套的Python标量列表返回
# x.tolist()

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.itemset.html#numpy.ndarray.itemset
# ndarray.itemset(*args)  将标量插入数组（如果可能，将标量转化为数组的dtype类型）
# x.itemset(x.shape[0],x.shape[1])
# x.item(1,2)

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html#numpy.ndarray.tostring
# ndarray.tostring([order]）  构造包含数组中原始数据字节的Python字节
# x.tostring("A")   # order must be one of 'C', 'F', 'A', or 'K'

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.tobytes.html#numpy.ndarray.tobytes
# ndarray.tobytes([order]）  构造包含数组中原始数据字节的Python字节
# x.tobytes("A")

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.tofile.html#numpy.ndarray.tofile
# ndarray.tofile(fid[, sep, format]) 将数组作为文本或二进制写入文件（默认）。
# x.tofile("array.txt",sep=",",format="%.2f")

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.dump.html#numpy.ndarray.dump
# ndarray.dump(file)  将数组的pickle转储到指定的文件
# x.dump("array_pickle.txt")

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype
# ndarray.astype(dtype[, order, casting, …])  数组的副本强制转换为指定类型
# x.astype(np.float32)

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.byteswap.html#numpy.ndarray.byteswap
# ndarray.byteswap([inplace])  交换数组元素的字节
# x.byteswap(4)    #inplace：字节数

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy
# ndarray.copy([order])  返回数组的副本。
# x.copy()


#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.view.html#numpy.ndarray.view
# ndarray.view([dtype, type]) 具有相同数据的数组的新视图
# x.view(int)
# x.view(np.int32)

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.getfield.html#numpy.ndarray.getfield
#ndarray.getfield(dtype[,offset]) 返回给定数组的字段作为特定的类型
# x.getfield(np.int,0)

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.setflags.html#numpy.ndarray.setflags
# ndarray.setflags([write, align, uic]) 分别设置数组标志 WRITEABLE、ALIGNED、WRITEBACKIFCOPY。

# x.setflags()  #

#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.fill.html#numpy.ndarray.fill
# ndarray.fill(value)	使用标量值填充数组。
# x.fill(0)
# x
x

NameError: name 'x' is not defined

In [26]:
# 形状操作
#参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape
# ndarray.reshape(shape[, order])	返回包含具有新形状的相同数据的数组。
# x.reshape(1,6) #返回数组，对原数组不进行修改

# 参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html#numpy.ndarray.resize
# ndarray.resize(new_shape[, refcheck])	就地更改数组的形状和大小。
# x.resize(3,2)   #不返回数组，对原数组进行修改
# x

# 参考文档：https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.html#numpy.ndarray.transpose
# ndarray.transpose(*axes) 返回轴转置的数组视图
# x.transpose()    #等于x.T


# ndarray.swapaxes(axis1:int, axis2:int)    返回数组的视图，其中axis1轴和axis轴互换。
# print(x)
# x.swapaxes(0,1)

t=np.array([[[1,2,3],[4,5,6]],[[0,0,0],[3,2,1]]])
print(t)
t.swapaxes(0,1)
t


[[[1 2 3]
  [4 5 6]]

 [[0 0 0]
  [3 2 1]]]


array([[0, 0, 0],
       [3, 2, 1]])