In [6]:
import numpy as np
import time
start=time.time()
s=[]
for x in range(1000000):
    s.append(x**2)
endtime=time.time()
print(endtime-start)

0.7855167388916016


In [7]:
s1=time.time()
np.arange(1000000)**2
e1=time.time()
print(e1-s1)

0.014007329940795898


In [8]:
np.array([1,2,"3"])


array(['1', '2', '3'], dtype='<U11')

In [11]:
a=np.array([1,2,"3"],dtype="int64")

array([1, 2, 3], dtype=int64)

In [15]:
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [13]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#random函数的用法
#np.random.random([(行，列)])：生成一个0-1之间的小数,[]:生成几行几列的矩阵（可选）
c=np.random.random()#生成随机数
c

0.05304192500245597

In [20]:
c=np.random.random((2,2))  #返回两行两列的数组
c

array([[0.24921122, 0.2251848 ],
       [0.46584947, 0.60362464]])

In [21]:
#np.random.randint(start,end,[size=()])：生成其实索引start到结束索引end之间的随机整数,[]:生成几行几列的矩阵（可选）
a=np.random.randint(0,9,size=(3,4))
print(a)

[[2 5 8 0]
 [0 6 4 3]
 [3 6 6 6]]


In [24]:
# numpy特殊函数
# 1、零矩阵
# array_zeros=np.zeros([(行、列)])
array_zeros=np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# 1矩阵
# array_one=np.zeros([(行、列)])
array_one=np.ones((4,4))
print(array_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#满矩阵
# array_full=np.full([(行，列)]，要生成的数值几)、
array_full=np.full((3,4),3)
print(array_full)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [28]:
#对称矩阵
# array_eye=np.eye(矩阵数)
array_eye=np.eye(4)
print(array_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
#数组输出类型dtype
a=np.arange(10)
a.dtype





dtype('int32')

In [31]:
#类型转换
b=a.astype("float64")
b.dtype

dtype('float64')

In [32]:
a.dtype

dtype('int32')

In [45]:
#多维数组
a1=np.array(
[1,2,3,4,5,6]
)
a2=np.array(
[
    [1,2,3],
    [4,5,6]
]
)
a3=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,3,1]
    ]
])
#查看数组的维度  ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
#查看数组的形状  shape
print(a1.shape)
print(a2.shape)
print(a3.shape)
#修改数组的形状  reshape
print(a1.reshape((2,3)))
print(a2.reshape((3,2)))
print(a3.reshape((12,)))
#修改数组的维度(直接降为一维) flatten
print(a3.flatten())
#获得数组元素个数  size
print(a3.size)
#获得数组字节数  itemsize
print(a3.itemsize)

#测算a3占用的粽子节数
total=a3.size*a3.itemsize
print(total)




1
2
3
(6,)
(2, 3)
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3  4  5  6  7  8  9 10  3  1]
[ 1  2  3  4  5  6  7  8  9 10  3  1]
12
4
48


In [62]:
b1=np.random.randint(0,10,size=(5,6))
print(b1)
#矩阵[行，列]  其中行又可以写成[索引行1，索引行2.,....]，列又可以写成[索引列1,索引列2,....] 
# 矩阵[起始索引行:结束索引行,起始索引列:结束索引列]   获取连续行对应连续列的值

#获取第一行的数据
print(b1[0])
#获取第三行、第五行的数据
print(b1[[1,4]])
#获取第一列的数据
print(b1[:,0])
#获取第一列、第三列的数据
print(b1[:,[0,2]])
#获得第二行第五行、第三列、第六列的数据
print(b1[[1,4],[2,5]])

[[0 9 8 8 1 1]
 [3 6 4 7 8 5]
 [7 5 3 4 8 6]
 [3 2 1 9 9 2]
 [1 2 4 6 5 6]]
[4 6]


In [69]:
#numpy的布尔索引
b2=np.arange(24).reshape(3,8)
print(b2)
#获取小于15的数字
print(b2[b2<15])
#大于10的和小于3的
print(b2[(b2<3) | (b2 >10)])


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [75]:
#值替换
b3=np.random.randint(0,10,size=(3,4))
print(b3)
#将某一行全部变为具体值  b3[要变的行]=值
b3[1]=0
print(b3)
#将某一行变成连续的值
b3[1]=np.arange(4)
print(b3)
#条件判断  
b3[b3<4]=1
print(b3)
#where函数的使用   where(数组判断(布尔值)，如果为真要替换的值，如果为假要替换的值)
np.where(b3<5,0,1)

[[0 3 1 2]
 [3 5 5 7]
 [1 1 4 7]]
[[0 3 1 2]
 [0 0 0 0]
 [1 1 4 7]]
[[0 3 1 2]
 [0 1 2 3]
 [1 1 4 7]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 4 7]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [105]:
# 作业
# 1、
c=np.arange(10)
c[c%2==1]=-1
print(c)
# 2、
c1=np.random.randint(0,10,size=(4,4))
print(c1)
print(c1[np.eye(4)==1])
# 3、
c1[[0,1,3],[0,2,1]]
# 4、
c1[2:4,:]
# 5、
c1=np.random.randint(0,10,size=(8,9))
print(c1)
c1[1:6,8][c1[1:6,8]>3]


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[6 4 0 0]
 [8 5 4 8]
 [2 3 1 3]
 [8 0 5 2]]
[6 5 1 2]
[[1 5 4 1 8 2 5 8 0]
 [3 7 0 5 9 4 5 2 8]
 [8 4 3 9 0 6 1 1 0]
 [3 1 6 6 8 6 8 3 9]
 [9 7 6 3 6 1 9 5 6]
 [9 3 0 3 2 7 5 5 2]
 [9 7 7 3 4 2 5 8 4]
 [0 9 7 6 5 0 0 6 4]]


array([8, 9, 6])

# numpy的广播机制

## 数组与数的运算(乘、减、加都可以)

In [7]:


import numpy as np

#相同维数矩阵相加
a1=np.random.randint(0,10,size=(5,6))
a2=np.random.randint(0,10,size=(5,6))
print(a1)
print("*"*30)
print(a2)
print("*"*30)
print(a1+a2)

[[6 8 6 6 6 7]
 [1 9 9 1 9 9]
 [0 5 2 5 4 2]
 [3 3 2 1 4 0]
 [0 9 5 1 8 1]]
******************************
[[4 1 1 4 1 4]
 [0 5 7 3 2 4]
 [6 4 6 4 5 4]
 [7 9 7 8 1 3]
 [7 7 4 7 7 8]]
******************************
[[10  9  7 10  7 11]
 [ 1 14 16  4 11 13]
 [ 6  9  8  9  9  6]
 [10 12  9  9  5  3]
 [ 7 16  9  8 15  9]]


In [8]:
#列为1相加
a3=np.random.randint(0,10,size=(5,1))
print(a3)
print("*"*30)
print(a1+a3)

[[8]
 [1]
 [7]
 [9]
 [3]]
******************************
[[14 16 14 14 14 15]
 [ 2 10 10  2 10 10]
 [ 7 12  9 12 11  9]
 [12 12 11 10 13  9]
 [ 3 12  8  4 11  4]]


In [10]:
#行为1相加
a4=np.random.randint(0,10,size=(1,6))
print(a1)
print("*"*30)
print(a4)
print("*"*30)
print(a1+a4)


[[6 8 6 6 6 7]
 [1 9 9 1 9 9]
 [0 5 2 5 4 2]
 [3 3 2 1 4 0]
 [0 9 5 1 8 1]]
******************************
[[1 4 6 5 8 8]]
******************************
[[ 7 12 12 11 14 15]
 [ 2 13 15  6 17 17]
 [ 1  9  8 10 12 10]
 [ 4  7  8  6 12  8]
 [ 1 13 11  6 16  9]]


In [13]:
#数组形状的操作
#reshape  和 resize
b=np.random.randint(0,10,size=(5,6))
print(b)
print("************")
print(b.reshape(6,5))
print(b)
print("************")
b.resize(6,5)
print(b)
print("************")
#总结  reshape()将数组变形后不会改变原函数,而resize()将数组变形后会改变原函数  

[[9 6 2 5 5 5]
 [6 3 0 9 9 7]
 [6 8 0 1 5 9]
 [5 7 3 0 9 1]
 [4 1 7 6 2 8]]
************
[[9 6 2 5 5]
 [5 6 3 0 9]
 [9 7 6 8 0]
 [1 5 9 5 7]
 [3 0 9 1 4]
 [1 7 6 2 8]]
[[9 6 2 5 5 5]
 [6 3 0 9 9 7]
 [6 8 0 1 5 9]
 [5 7 3 0 9 1]
 [4 1 7 6 2 8]]
************
[[9 6 2 5 5]
 [5 6 3 0 9]
 [9 7 6 8 0]
 [1 5 9 5 7]
 [3 0 9 1 4]
 [1 7 6 2 8]]
************


In [20]:
#flatten() 和 ravel()
c=np.random.randint(0,10,size=(3,5))
# print(c)

print("************")
d=c.flatten()
print(d)
d[10]=100
print(d)
print(c.flatten())
print("************")
e=c.ravel()
print(e)

e[10]=20
print(e)
print(e.ravel())

#flatten()和ravel()的区别
#         flatten() 将数据降成一维后，对数据进行修改，并不会改变原来的值
#         ravel()   将数据降成一维后，对数据进行修改，会改变原来的值







************
[7 8 7 9 6 3 3 7 5 5 9 6 2 3 5]
[  7   8   7   9   6   3   3   7   5   5 100   6   2   3   5]
[7 8 7 9 6 3 3 7 5 5 9 6 2 3 5]
************
[7 8 7 9 6 3 3 7 5 5 9 6 2 3 5]
[ 7  8  7  9  6  3  3  7  5  5 20  6  2  3  5]
[ 7  8  7  9  6  3  3  7  5  5 20  6  2  3  5]


In [42]:
#不同数组的组合
# vstack() 、hstack() 和 concatenate()
a1=np.random.randint(0,10,size=(4,6))
a2=np.random.randint(0,10,size=(1,6))
print(a1)
print("**************")
print(a2)
print("**************")
# vstack()为纵轴合并
print(np.vstack([a1,a2]))
print("******************************")
# hstack()为横轴合并
a3=np.random.randint(0,10,size=(4,1))
print(a3)
print(np.hstack([a1,a3]))
print("**************")
#axis=1为横向合并  axis=0为纵向合并
print(np.concatenate((a1,a2),axis=0))
print(np.concatenate((a1,a3),axis=1))








[[5 1 4 2 0 2]
 [2 6 8 0 7 9]
 [5 1 6 5 2 8]
 [9 7 7 6 0 2]]
**************
[[1 8 6 1 8 9]]
**************
[[5 1 4 2 0 2]
 [2 6 8 0 7 9]
 [5 1 6 5 2 8]
 [9 7 7 6 0 2]
 [1 8 6 1 8 9]]
******************************
[[6]
 [1]
 [5]
 [0]]
[[5 1 4 2 0 2 6]
 [2 6 8 0 7 9 1]
 [5 1 6 5 2 8 5]
 [9 7 7 6 0 2 0]]
**************
[[5 1 4 2 0 2]
 [2 6 8 0 7 9]
 [5 1 6 5 2 8]
 [9 7 7 6 0 2]
 [1 8 6 1 8 9]]
[[5 1 4 2 0 2 6]
 [2 6 8 0 7 9 1]
 [5 1 6 5 2 8 5]
 [9 7 7 6 0 2 0]]


In [44]:
#数组的切割
# hsplit() 、vsplit() 和 array_split()
a1=np.random.randint(0,10,size=(4,4))
print(a1)
print(np.vsplit(a1,2))
print("**************")
print(np.hsplit(a1,2))
print("**************")
print(np.array_split(a1,2,axis=1))   #横轴切割
print("**************")
print(np.array_split(a1,2,axis=0)) #纵轴切割



[[2 4 1 7]
 [7 7 7 6]
 [2 7 9 6]
 [6 0 3 4]]
[array([[2, 4, 1, 7],
       [7, 7, 7, 6]]), array([[2, 7, 9, 6],
       [6, 0, 3, 4]])]
**************
[array([[2, 4],
       [7, 7],
       [2, 7],
       [6, 0]]), array([[1, 7],
       [7, 6],
       [9, 6],
       [3, 4]])]
**************
[array([[2, 4],
       [7, 7],
       [2, 7],
       [6, 0]]), array([[1, 7],
       [7, 6],
       [9, 6],
       [3, 4]])]
**************
[array([[2, 4, 1, 7],
       [7, 7, 7, 6]]), array([[2, 7, 9, 6],
       [6, 0, 3, 4]])]


In [58]:
#数组（矩阵）转置与轴兑换
#转置:矩阵.T  或 transpose()
#求内积：矩阵1.dot(矩阵2)

a=np.arange(0,20).reshape((4,5))
print(a)
print("**************")
#转置
b=a.T
print(b)
print("**************")

b[0]=100
print(b)
print("**************")
print(a)
print("--------------")
print("**************")
a=np.arange(0,20).reshape((4,5))
c=a.transpose()
print(c)
c[0]=20
print(c)
print(a)
# #求内积
# print(a.dot(b))

# a.T和a.transpose()区别(无区别)
#         a.T ： 对转置后的数组修改不会影响原数组
#         transpose()： 对转置后的数组修改不会影响原数组


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
**************
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
**************
[[100 100 100 100]
 [  1   6  11  16]
 [  2   7  12  17]
 [  3   8  13  18]
 [  4   9  14  19]]
**************
[[100   1   2   3   4]
 [100   6   7   8   9]
 [100  11  12  13  14]
 [100  16  17  18  19]]
--------------
**************
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[20 20 20 20]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[20  1  2  3  4]
 [20  6  7  8  9]
 [20 11 12 13 14]
 [20 16 17 18 19]]


In [66]:
#深浅拷贝
# 1、不拷贝（只是换了个名字，赋值语句）
a=np.random.randint(0,10,size=(3,4))
b=a
print(a)
print(b)
print("**************")
# 2、浅拷贝  view()只拷贝栈区，不拷贝堆区
c=a.view()   
c[0]=1
print(c)
print(a)
print("**************")
#3、深拷贝
d=a.copy()
d[1]=2
print(a)
print(d)


[[2 8 1 7]
 [6 9 5 3]
 [9 6 1 6]]
[[2 8 1 7]
 [6 9 5 3]
 [9 6 1 6]]
**************
[[1 1 1 1]
 [6 9 5 3]
 [9 6 1 6]]
[[1 1 1 1]
 [6 9 5 3]
 [9 6 1 6]]
**************
[[1 1 1 1]
 [6 9 5 3]
 [9 6 1 6]]
[[1 1 1 1]
 [2 2 2 2]
 [9 6 1 6]]
