In [4]:
# Series对象的创建
import pandas as pd
# 通过列表进行创建
s1=pd.Series([1,2,3,4,5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [8]:
#通过数组创建
import numpy as np
a=np.arange(1,6)
print(a)
s1=pd.Series(a)
print(s1)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int32


In [10]:
#通过字典创建
dict={"name":"zhang3","age":18,"salary":2000}
data=pd.Series(dict,index=["name",'age','salary','sex'])  #索引长度和数组长度必须相同
print(data)


name      zhang3
age           18
salary      2000
sex          NaN
dtype: object


In [13]:
#  Series对象基本用法
#isnull() 和 notnull() 检查缺失值
res=pd.isnull(data)  #判断是否为空，如果为空为True
print(res)
res=pd.notnull(data)#判断是否为空，如果不为空为True
print(res)

name      False
age       False
salary    False
sex        True
dtype: bool
name       True
age        True
salary     True
sex       False
dtype: bool


In [31]:
# 通过索引获取数据
print(data.index)
print(data.values)
# 通过下标获取数据
print(data[1])
# 通过索引值获取数据
print(data["name"])
# 选取多个(根据下标选取)
print(data[[1,3]])
# 选取多个(通过索引值获取数据)
print(data[["name","age"]])

# 切片
print(data[1:3])  #下标切片不包括3

print(data["name":"salary"])  #包括所有数据


Index(['name', 'age', 'salary', 'sex'], dtype='object')
['zhang3' 18 2000 nan]
18
zhang3
age     18
sex    NaN
dtype: object
name    zhang3
age         18
dtype: object
age         18
salary    2000
dtype: object
name      zhang3
age           18
salary      2000
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int32
2    3
3    4
4    5
dtype: int32


In [32]:
#布尔索引
a=np.arange(1,6)
s1=pd.Series(a)
print(s1)
print(s1[s1>2])   #当值为数字时，布尔索引才起作用

0    1
1    2
2    3
3    4
4    5
dtype: int32
2    3
3    4
4    5
dtype: int32


In [38]:
#起索引名
s1.name="薪水表"
s1.index.name="索引"
s1
print(s1*2)  #对series的数据乘以2
# head([num]) 函数   num:获得前几行的元素，如果不写则显示全部
print(s1.head())
print(s1.head(3))
# tail(num) 函数   num:获得后几行的元素，如果不写则显示全部
print(s1.tail())
print(s1.tail(2))

索引
0     2
1     4
2     6
3     8
4    10
Name: 薪水表, dtype: int32
索引
0    1
1    2
2    3
3    4
4    5
Name: 薪水表, dtype: int32
索引
0    1
1    2
2    3
Name: 薪水表, dtype: int32
索引
0    1
1    2
2    3
3    4
4    5
Name: 薪水表, dtype: int32
索引
3    4
4    5
Name: 薪水表, dtype: int32


In [40]:
# DataFrame的使用
#字典类
#     数组、列表、元组构成的字典构成DataFrame
#     Series构成的字典构成DataFrame
#     字典构成的字典构成DataFrame
    
# 列表类
#     2维nadarray构造DataFrame
#     字典构造的列表构造DataFrame
#     Series构成的列表构成DataFrame

In [65]:
# 数组、列表、元组构成的字典构成DataFrame
import numpy as np
import pandas as pd
d={
    "name":["zhang3",'lisi','tom'],
    "age":[13,21,26],
    "salary":np.arange(2000,2003)
}
df=pd.DataFrame(d)
df
print(df.index)   #获得行索引
print(df.columns)  #获得列索引
print(df.values)  #获得值


#指定行索引或列索引   行索引:index=["索引1",'索引2',....]   列索引:columns=["索引1",'索引2',.....]
d=np.arange(9).reshape(3,3)
print(d)
df=pd.DataFrame(d,index=["a",'b','c'],columns=["A",'B','C'])
print(df)

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'salary'], dtype='object')
[['zhang3' 13 2000]
 ['lisi' 21 2001]
 ['tom' 26 2002]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [73]:
# Series构成的字典构成DataFrame
s1=np.arange(1,10)
df=pd.DataFrame({"a":pd.Series(s1),
                "b":pd.Series(np.arange(3,7))})  #s1只能是一维的
print(df)


   a    b
0  1  3.0
1  2  4.0
2  3  5.0
3  4  6.0
4  5  NaN
5  6  NaN
6  7  NaN
7  8  NaN
8  9  NaN


In [81]:
# 字典构成的字典构成DataFrame   (键代表行，最后值代表列)
dict1={
        "a":{
            "apple":22,"banana":30
        },
          "b":{
            "apple":31,"banana":21
        },
          "c":{
            "apple":33,"banana":26
        },
          "d":{
            "apple":35,"banana":37
        },
     }
df=pd.DataFrame(dict1)
print(df)


         a   b   c   d
apple   22  31  33  35
banana  30  21  26  37


In [85]:
#列表类
#     2二维 nadarray构造DataFrame
data=np.arange(24).reshape(4,6)
df=pd.DataFrame(data,index=["a",'b','c','d'],columns=["A","B","C","D","E","F"])
print(df)



    A   B   C   D   E   F
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23


In [108]:
# 字典构造的列表构造DataFrame
dict1=[
     {
        "apple":22,"banana":30
        },
        {
            "apple":31,"banana":21
        },
          {
            "apple":33,"banana":26
        },
          {
            "apple":35,"banana":37
        }
]

df=pd.DataFrame(dict1)
print(df)

   apple  banana
0     22      30
1     31      21
2     33      26
3     35      37


In [3]:
import pandas as pd
import numpy as np
# Series构成的列表构成DataFrame
df=pd.DataFrame([pd.Series(np.arange(4)),pd.Series(np.random.rand(4))])
print(df)

          0         1         2         3
0  0.000000  1.000000  2.000000  3.000000
1  0.580408  0.777054  0.144609  0.964691


In [104]:
#转置  (行和列转置)
df.T

0         1
0  0.0  0.919652
1  1.0  0.220166
2  2.0  0.970160
3  3.0  0.493411

In [4]:
print(df[0])#取得列数

0    0.000000
1    0.580408
Name: 0, dtype: float64


In [112]:
df=pd.DataFrame(data,index=["a",'b','c','d'],columns=["A","B","C","D","E","F"])
print(df)

    A   B   C   D   E   F
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23


In [113]:
df["A"]

a     0
b     6
c    12
d    18
Name: A, dtype: int32

In [115]:
df["G"]=9  #增加列并赋值
df

A   B   C   D   E   F  G
a   0   1   2   3   4   5  9
b   6   7   8   9  10  11  9
c  12  13  14  15  16  17  9
d  18  19  20  21  22  23  9

In [116]:
df["G"]=[1,2,3,4]  #增加列并赋值
df

A   B   C   D   E   F  G
a   0   1   2   3   4   5  1
b   6   7   8   9  10  11  2
c  12  13  14  15  16  17  3
d  18  19  20  21  22  23  4

In [117]:
del(df["G"])  #删除列
df



A   B   C   D   E   F
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23

In [118]:
#索引对象是不可改变的
df.index["A"]="Q"
df

TypeError: Index does not support mutable operations

In [10]:
# 索引的基本操作
# 增、删、改、查
# reindex()重建新的索引，新的行索引需要使用旧的索引

df=pd.DataFrame(np.arange(9).reshape(3,3),index=["a",'b','c'],columns=['A','B','C'])
# df
df1=df.reindex(["a",'b','c','d'])  #返回创建新的索引,新的行索引需要使用旧的索引
df1

df2=df.reindex(columns=["C",'A','B']) #返回创建新的索引,新的列索引需要使用旧的索引
# df2





In [162]:
#增


# Series
#改变原Series
ps=pd.Series(np.arange(5),index=["a",'b','c','d','e'])
ps["g"]=20  
ps

#不改变原Series
ps2=pd.Series({'h':30}) 
ps3=ps.append(ps2)
ps3
ps

# DataFrame
#改变原DataFrame


# 增加列
df=pd.DataFrame(np.arange(9).reshape(3,3),index=["a",'b','c'],columns=['A','B','C'])
df["E"]=5 #插入一列  
df["F"]=[1,2,3]  #插入一列  
df
# 在指定列索引前插入    insert(索引值,索引名，索引数据)
df.insert(0,'G',[7,23,5])
df
# 增加行
# 标签索引 loc
df.loc['d']=[1,1,1,1,1,1]
print(df)

#不改变原DataFrame
row={"G":11,"A":20,"B":10,'C':35,'E':21,'F':30}
df1=df.append(row,ignore_index=True)
df1


    G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3
d   1  1  1  1  1  1


G   A   B   C   E   F
0   7   0   1   2   5   1
1  23   3   4   5   5   2
2   5   6   7   8   5   3
3   1   1   1   1   1   1
4  11  20  10  35  21  30

In [153]:
ps

a     0
b     1
c     2
d     3
e     4
g    20
dtype: int64

In [8]:
# 删除


# Series
#改变原Series
# del ps['g']
# ps


#不改变原Series
#删除一条
# ps1=ps.drop("e")
# ps1
# #删除多条
# ps1=ps.drop(["e",'a','b'])
# ps1

# DataFrame
# 改变原DataFrame
# del df1['G']
print(df1)


# 不改变原DataFrame
# drop删除数据   inplace属性：决定在原对象上删除，就不会返回一个新的对象 

# (行)
#删除一条
df2=df1.drop(4)

#删除多条
df2=df1.drop([3,4])
print(df2)

# 删除列
#删除一条
df2=df1.drop("A",axis=1)
df2
#删除多条
df2=df1.drop(["A",'B'],axis=1)
df2

# 或者
df2=df1.drop(["A",'B'],axis='columns')  #axis='columns' 等于 axis=1   axis=‘index’等于 axis=0
df2


ps1.drop("d",inplace=True)
ps1

     A    B    C
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN


KeyError: '[4] not found in axis'

In [199]:
#改

#改变原Series
#通过索引改变
ps1["c"]=999
#通过下标改变
ps1[0]=777
ps1


# 改变原DataFrame
#第一种写法
df1['A']=1
# print(df1)
df1['A']=[1,2,3,4,5]
df1
#第二种写法(对象加列)
df1.A=10
print(df1)

#获取行数据
print(df1.loc[1])
# 获取某行某列数据
print(df1.loc[1,"C"])
#修改行数据 loc
df1.loc[1]=233
df1
#修改某行某列的值  df1.loc["行索引","列索引"]
df1.loc[1,"A"]=20
df1


    A    B    C    E    F
0  10    1    2    5    1
1  10  233  233  233  233
2  10    7    8    5    3
3  10    1    1    1    1
4  10   10   35   21   30
A     10
B    233
C    233
E    233
F    233
Name: 1, dtype: int64
233


A    B    C    E    F
0  10    1    2    5    1
1  20  233  233  233  233
2  10    7    8    5    3
3  10    1    1    1    1
4  10   10   35   21   30

In [207]:
#查
# Series
# 1、行索引
# 标签索引
ps['a']
# 下标索引 
ps[0]
# 切片索引

ps[0:2]  #使用下标

print(ps["b":"d"])  #按照索引名切片包含终止索引

#不连续索引
ps[[0,2]]
ps[['a','d']]


b    1
c    2
d    3
dtype: int64


a    0
d    3
dtype: int64

In [208]:
 #布尔索引   (按值索引)
ps[ps>2]

d    3
e    4
dtype: int64

In [209]:
# DataFrame
df

G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3
d   1  1  1  1  1  1

In [215]:
#取一列
df['A']
#取多列
df[['A','B']]
#切片
df[:2]   #获取行




G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2

In [211]:
df.loc["a","A"]  #取某一个值

0

In [212]:
df.loc['a']   #取一行

G    7
A    0
B    1
C    2
E    5
F    1
Name: a, dtype: int64

In [216]:
df.loc[['a','c']]   #取多行

G  A  B  C  E  F
a  7  0  1  2  5  1
c  5  6  7  8  5  3

In [217]:
df.loc['a':'c']   #取多行

G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3

In [219]:
df["a":'c']  #标签索引

G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3

In [226]:

#取某行某列数据(一行一列)
df_one=df.loc["a","A"]
print(df_one)
#取某行某列数据(多行一列)
print(df)
df.loc['a':'d','A']
#取某行某列数据(多行多列)
df.loc["a":'d',"A":"C"]

0
    G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3
d   1  1  1  1  1  1


A  B  C
a  0  1  2
b  3  4  5
c  6  7  8
d  1  1  1

In [228]:
#iloc 位置索引
# Series
ps[1:3]
ps.iloc[1:3]

b    1
c    2
dtype: int64

In [232]:
# DataFrame
df.iloc[1:3,0]   #iloc[行索引，列索引]



b    23
c     5
Name: G, dtype: int64

In [247]:
#ix标签与位置混合索引
# Series
ps.ix[1:3]
ps.ix['b':'c']



F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


a    0
b    1
c    2
d    3
e    4
dtype: int64

In [245]:
# DataFrame
df.ix[1:3,"A"]#ix[行索引，列索引]
df


F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3
d   1  1  1  1  1  1

In [13]:

#按行索引对齐
# Series
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
s1+s2   #未有的列填充NaN
# add()、radd() 加法运算  
s1.add(s2,fill_value=0) #fill_value填充0，即可正常显示
s2.radd(s1,fill_value=0)   #radd():翻转
# DataFrame
print(df1,'*')
print(df2,'**')
df1+df2 
#不显示有NaN值
print(df1.add(df2,fill_value=0))
df2.radd(df1,fill_value=0)

df1.reindex(columns=df2.columns,fill_value=0)  #通过df2索引获取相关df1索引的值(类似于表链接查询)  


     A    B    C
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN *
   C  A  B
a  2  0  1
b  5  3  4
c  8  6  7 **
      A     B     C
a   0.0   2.0   4.0
b   6.0   8.0  10.0
c  12.0  14.0  16.0
d   NaN   NaN   NaN


C    A    B
a  2.0  0.0  1.0
b  5.0  3.0  4.0
c  8.0  6.0  7.0
d  NaN  NaN  NaN

In [277]:
# DataFrame和Series的混合运算
arr=np.arange(12).reshape(3,4)
arr
arr-arr[0] #numpy的广播机制
s1=df.iloc[0]
print(df)
print(s1)
#广播运算 (沿着行向下运算)
df-s1
#广播运算 (沿着列向下运算)
s2=df['A']
df.sub(s2,axis=0)


    G  A  B  C  E  F
a   7  0  1  2  5  1
b  23  3  4  5  5  2
c   5  6  7  8  5  3
d   1  1  1  1  1  1
G    7
A    0
B    1
C    2
E    5
F    1
Name: a, dtype: int64


G  A  B  C  E  F
a   7  0  1  2  5  1
b  20  0  1  2  2 -1
c  -1  0  1  2 -1 -3
d   0  0  0  0  0  0